# coding: utf-8

"""
    Clinic Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClientUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'object',
        'document': 'object',
        'sur_name': 'object',
        'first_name': 'object',
        'patronymic': 'object',
        'birthday': 'object'
    }

    attribute_map = {
        'client_id': 'client_id',
        'document': 'document',
        'sur_name': 'sur_name',
        'first_name': 'first_name',
        'patronymic': 'patronymic',
        'birthday': 'birthday'
    }

    def __init__(self, client_id=None, document=None, sur_name=None, first_name=None, patronymic=None, birthday=None):  # noqa: E501
        """ClientUpdate - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._document = None
        self._sur_name = None
        self._first_name = None
        self._patronymic = None
        self._birthday = None
        self.discriminator = None
        self.client_id = client_id
        if document is not None:
            self.document = document
        if sur_name is not None:
            self.sur_name = sur_name
        if first_name is not None:
            self.first_name = first_name
        if patronymic is not None:
            self.patronymic = patronymic
        if birthday is not None:
            self.birthday = birthday

    @property
    def client_id(self):
        """Gets the client_id of this ClientUpdate.  # noqa: E501


        :return: The client_id of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this ClientUpdate.


        :param client_id: The client_id of this ClientUpdate.  # noqa: E501
        :type: object
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def document(self):
        """Gets the document of this ClientUpdate.  # noqa: E501


        :return: The document of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this ClientUpdate.


        :param document: The document of this ClientUpdate.  # noqa: E501
        :type: object
        """

        self._document = document

    @property
    def sur_name(self):
        """Gets the sur_name of this ClientUpdate.  # noqa: E501


        :return: The sur_name of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._sur_name

    @sur_name.setter
    def sur_name(self, sur_name):
        """Sets the sur_name of this ClientUpdate.


        :param sur_name: The sur_name of this ClientUpdate.  # noqa: E501
        :type: object
        """

        self._sur_name = sur_name

    @property
    def first_name(self):
        """Gets the first_name of this ClientUpdate.  # noqa: E501


        :return: The first_name of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ClientUpdate.


        :param first_name: The first_name of this ClientUpdate.  # noqa: E501
        :type: object
        """

        self._first_name = first_name

    @property
    def patronymic(self):
        """Gets the patronymic of this ClientUpdate.  # noqa: E501


        :return: The patronymic of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._patronymic

    @patronymic.setter
    def patronymic(self, patronymic):
        """Sets the patronymic of this ClientUpdate.


        :param patronymic: The patronymic of this ClientUpdate.  # noqa: E501
        :type: object
        """

        self._patronymic = patronymic

    @property
    def birthday(self):
        """Gets the birthday of this ClientUpdate.  # noqa: E501


        :return: The birthday of this ClientUpdate.  # noqa: E501
        :rtype: object
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday):
        """Sets the birthday of this ClientUpdate.


        :param birthday: The birthday of this ClientUpdate.  # noqa: E501
        :type: object
        """

        self._birthday = birthday

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
