# coding: utf-8

"""
    Clinic Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clinic_api
from clinic_api.api.consultation_api import ConsultationApi  # noqa: E501
from clinic_api.rest import ApiException


class TestConsultationApi(unittest.TestCase):
    """ConsultationApi unit test stubs"""

    def setUp(self):
        self.api = ConsultationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_consultation_create(self):
        """Test case for consultation_create

        Create  # noqa: E501
        """
        pass

    def test_consultation_delete(self):
        """Test case for consultation_delete

        Delete  # noqa: E501
        """
        pass

    def test_consultation_get_all(self):
        """Test case for consultation_get_all

        Get All  # noqa: E501
        """
        pass

    def test_consultation_get_by_id(self):
        """Test case for consultation_get_by_id

        Get By Id  # noqa: E501
        """
        pass

    def test_consultation_update(self):
        """Test case for consultation_update

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
