# coding: utf-8

"""
    Clinic Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clinic_api
from clinic_api.models.client_update import ClientUpdate  # noqa: E501
from clinic_api.rest import ApiException


class TestClientUpdate(unittest.TestCase):
    """ClientUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientUpdate(self):
        """Test ClientUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clinic_api.models.client_update.ClientUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
